name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get the version
      id: get_version
      run: |
        echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd resting-catt
        docker build . --file Dockerfile --tag eliseomartelli/base:${{ steps.get_version.outputs.VERSION }}
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push eliseomartelli/base:${{ steps.get_version.outputs.VERSION }}
